name: 'Coverage Action Comments'
description: 'Coverage Action Comments on the Pull requests'
author: 'vinialves008'

# Define your inputs here.
inputs:
  GITHUB_TOKEN:
    description: 'Your input description here'
    required: true

# Define your outputs here.
outputs:
  time:
    description: 'Test coverage'

runs:
  using: node20
  main: dist/index.js
